/* eslint-disable eqeqeq */
/* eslint-disable no-plusplus */
/* eslint-disable no-restricted-syntax */
/* eslint-disable no-array-constructor */
/* eslint-disable no-underscore-dangle */
/**
 * Code generated by Resolve Studio S.A.S
 */
import KMeans from "skmeans";

class Classifier {
    constructor() {
        this._trainingData = null;
        this._vectors = new Array();
    }

    set trainingData(trainingData) {
        this._trainingData = trainingData;
        this._vectors = this.transformData();
    }

    transformData() {
        const vectors = new Array();
        for (let i = 0; i < this._trainingData.length; i++) {
            const info = new Array();
            for (const key in this._trainingData[i]) {
                if (key != "date") info.push(this._trainingData[i][key]);
            }
            vectors[i] = info;
        }
        return vectors;
    }

    classifier(testData) {
        const model = KMeans(this._vectors, 10, this._vectors[0]);
        const result = model.test(testData);
        return result;
    }
}

export default Classifier;
